apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mysql
  name: mysql
spec:
  ports:
  - name: 3606-3606
    port: 3606
    protocol: TCP
    targetPort: 3606
  selector:
    app: mysql
  clusterIP: None
status:
  loadBalancer: {}
